### ISSUE TITLE
Bug: Key Configuration

### ISSUE THREAD

**Issue by Jim2578** [acscripts/ac_radio#26]
### Version

v1.0.2

### Framework

ox_core

### Issue description

I installed ac-radio, the script works without problems except for one detail, I changed the basic configuration key (ALT) to Caps Lock. the problem is that not all players see their configuration change for some it works without problem, for others on the contrary it stays on the initial key and for others it goes to another key . Any idea how to fix this, I've already tried deleting the cache and the server cache

i'm on standalone no framework

### Steps to reproduce

1. Install the script
2. test then
3. change the key

### Confirm the following statements:

- [X] This issue is not a question or a feature request.
- [X] I have provided a **detailed** issue description and **detailed** reproduction steps.

**Comment by antond15** [comment]
This is not an issue related to ac_radio, nor an issue at all.
Changing default keybind key changes the default keybind key 🤯 If user already changed it from default to something else, it won't change.

You can change the command name to something new/unique in order to force the change for everyone (as it will create a new keybind entry).

**Comment by Jim2578** [comment]
Yes but i have any key in key configuration page for fivem, i talk about the kay to speak at the radio not to open then

**Comment by antond15** [comment]
It's the same, change the command name used for talking to radio (in pma-voice).
